apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.containerPort }}"
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        imagePullSecrets:
          - name: {{ .Values.image.pullSecret }}
        resources:
          limits:
            cpu: 1
            memory: 1G
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 1
