apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
    name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
