apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "service.labels" . | nindent 4 }}
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
          name: http 
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      restartPolicy: Always
