apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "service.labels" . | nindent 4 }}
  name: {{ include "service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
          name: http
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.port }}
          initialDelaySeconds: 2
          periodSeconds: 2
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      restartPolicy: Always
