apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ default .Release.Namespace }}
spec:
  gateways:
  {{- range .Values.istio.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
      - destination:
          port:
            number: {{ .Values.service.host }}
          host: {{ include "service.fullname" . }}.{{ default .Release.Namespace }}.svc.cluster.local
